version: '3.1'

services:

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8080:2368
    environment:
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
    volumes:
      - cooking-papa-content:/var/lib/ghost/content

      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
volumes:
  cooking-papa-content: